version: "3"
services:
#  traefik:
#    image: "traefik"
#    container_name: noname.traefik
#    command:
#      #- "--log.level=DEBUG"
#      - "--api.insecure=true"
#      - "--providers.docker=true"
#      - "--providers.docker.exposedbydefault=false"
#      - "--entrypoints.web.address=:80"
#    ports:
#      - "80:80"
#      - "8080:8080"
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  noname:
    build: .
    container_name: noname.noname
    expose:
      - 80
    ports:
      - "8000:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.noname.rule=Host(`local.awaitq.com`)"
      - "traefik.http.routers.noname.entrypoints=web"
