version: "3"
services:
  noname:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: noname
    volumes:
      - ./src/noname:/opt/noname/noname
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: "uvicorn noname.main:app --reload --host 0.0.0.0 --port 8000"
