version: "3"

volumes:
  db: {}


services:
  db:
    image: postgres:latest
    restart: always
    container_name: noname.test.db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    ports:
      - "5433:5432"
    # Use in memory storage to increase performance.
    # Important in tests.
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
    command: ["postgres", "-c", "log_statement=all"]
