version: "3"

volumes:
  db: {}


services:

  noname:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: noname
    volumes:
      - ./src/noname:/opt/noname/noname
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: "uvicorn noname.main:app --reload --host 0.0.0.0 --port 8000"

  db:
    image: postgres:latest
    restart: always
    container_name: noname.db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
