"""Second version.

Revision ID: 537e302516b8
Revises: 73958b7225bc
Create Date: 2022-12-22 20:30:41.203878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537e302516b8'
down_revision = '73958b7225bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author_name', sa.String(), nullable=True))
    op.drop_column('book', 'primary_author')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('primary_author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('book', 'author_name')
    # ### end Alembic commands ###
